const SIGNIN = 'user/SIGNIN'
const SIGNIN_SUCCESS = 'user/SIGNIN_SUCCESS'
const SIGNIN_FAILED = 'user/SIGNIN_FAILED'

const CHECK_TOKEN = 'user/CHECK_TOKEN'
const CHECK_TOKEN_SUCCESS = 'user/CHECK_TOKEN_SUCCESS'

const LOGOUT = 'user/LOGOUT'
const LOGOUT_SUCCESS = 'user/LOGOUT_SUCCESS'

export {
  SIGNIN,
  SIGNIN_SUCCESS,
  SIGNIN_FAILED,
  CHECK_TOKEN,
  CHECK_TOKEN_SUCCESS,
  LOGOUT,
  LOGOUT_SUCCESS,
}
