const GET_DATA_REQUEST = 'photos/GET_DATA_REQUEST';
const GET_DATA_REQUEST_SUCCESS = 'photos/GET_DATA_REQUEST_SUCCESS';
const GET_DATA_REQUEST_FAILED = 'photos/GET_DATA_REQUEST_FAILED';

export {GET_DATA_REQUEST, GET_DATA_REQUEST_SUCCESS, GET_DATA_REQUEST_FAILED};
